// <auto-generated />
namespace NewsFeedVn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addImage));
        
        string IMigrationMetadata.Id
        {
            get { return "202005241250402_addImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
